PracticeMovieDbProject/ViewModels/MovieViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using MovieData.Models;
using PracticeMovieDbProject.Models;

namespace PracticeMovieDbProject.ViewModels
{
    public enum PosterTypes
    {
        jpg,
        jpeg,
        png,
        gif,
        svg
    }

    public class MovieViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Name")]
        public string MovieName { get; set; }

        [Display(Name = "Plot")]
        public string Plot { get; set; }

        [Display(Name = "Release Year")]
        public int? ReleaseYear { get; set; }
        
        [DataType(DataType.ImageUrl, ErrorMessage = "Invalid image file")]
        [Display(Name = "Change Poster")]
        public string PosterUrl { get; set; }

        public IFormFile Poster { get; set; }

        public int NewProducerId { get; set; }

        public int CurrentProducerId { get; set; }

        public string ProducerName { get; set; }

        public string NewProducerDetails { get; set; }

        public string NewActorDetails { get; set; }

        public string CurrentPoster { get; set; }

        public string GlobalError { get; set; }

        public Producer NewProducer { get; set; }
                
        public List<ActorCheckboxModel> AllActors { get; set; }
        
        public List<Actor> MovieActors { get; set; }

        public List<Producer> Producers { get; set; }

        public PersonViewModel PersonViewModel { get; set; }        
    }
}

PracticeMovieDbProject/Controllers/ActorController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieData;
using PracticeMovieDbProject.ViewModels;

namespace PracticeMovieDbProject.Controllers
{
    public class ActorController : Controller
    {
        private IMovieService _movieDbService;
        private IActorService _actorDbService;
        private IProducerService _producerDbService;
        private IGenderService _genderDbService;

        public ActorController(IMovieService movies, IActorService actors, IProducerService producers, IGenderService genders)
        {
            _movieDbService = movies;
            _actorDbService = actors;
            _producerDbService = producers;
            _genderDbService = genders;
        }
        
        public IActionResult Index()
        {
            var actors = _actorDbService.GetAll();
            
            if (actors == null)
            {
                return RedirectToAction("Error", "Listing");
            }

            var listingResult = actors
                .Select(result => new PersonDetailsViewModel
                {
                    Id = result.Id,
                    Name = result.FullName,
                    DOB = result.DOB.ToString("MM/dd/yyyy"),
                    Age = result.Age,
                    Sex = result.Sex.Description,
                    Bio = result.Bio
                })
                .OrderBy(x => x.Name);

            var model = new ActorsListingViewModel()
            {
                Actors = listingResult
            };

            return View(model);
        }

        public IActionResult Detail(int? id)
        {
            if(!id.HasValue)
            {
                return RedirectToAction("Error", "Listing");
            }

            var actor = _actorDbService.GetById(id.Value);
            
            if(actor == null)
            {
                return RedirectToAction("Error", "Listing");
            }

            var model = new PersonDetailsViewModel
            {
                Id = actor.Id,
                Name = actor.FullName,
                DOB = actor.DOB.ToString("MM/dd/yyyy"),
                Age = actor.Age,
                Bio = actor.Bio,
                Sex = actor.Sex.Description,
                Movies = _actorDbService.GetActorMovies(id.Value)
            };

            return View(model);
        }
    }
}

PracticeMovieDbProject/Controllers/ListingController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieData;
using MovieData.Models;
using Newtonsoft.Json;
using PracticeMovieDbProject.Models;
using PracticeMovieDbProject.ViewModels;

namespace PracticeMovieDbProject.Controllers
{
    public class ListingController : Controller
    {
        private IMovieService _movieDbService;
        private IActorService _actorDbService;
        private IProducerService _producerDbService;
        private IGenderService _genderDbService;
        private IEnumerable<Gender> _genders;
        private IMappingService _mappingService;
        private Movie _currentMovie;
        private readonly IHostingEnvironment _hostingEnvironment;

        public ListingController(
            IMovieService movies,
            IActorService actors,
            IProducerService producers,
            IMappingService mappingService,
            IHostingEnvironment hostingEnvironment,
            IGenderService genders)
        {
            _movieDbService = movies;
            _actorDbService = actors;
            _producerDbService = producers;
            _genderDbService = genders;
            _mappingService = mappingService;
            _hostingEnvironment = hostingEnvironment;
            _genders = _genderDbService.GetGenders();
        }

        public IActionResult Index()
        {
            var moviesListing = _movieDbService.GetAll().OrderByDescending(x => x.Id);

            var listingResult = moviesListing
                .Select(result => new MovieViewModel
                {
                    Id = result.Id,
                    MovieName = result.Name,
                    PosterUrl = result.PosterUrl,
                    Plot = result.Plot,
                    ReleaseYear = result.ReleaseYear,
                    CurrentProducerId = result.Producer?.Id ?? 0,
                    ProducerName = result.Producer?.FullName,
                    MovieActors = result.Actors.ToList()
                });

            var model = new MovieListingViewModel()
            {
                Movies = listingResult
            };

            return View(model);
        }

        public IActionResult Movie(int id)
        {
            var movie = _movieDbService.GetById(id);

            if (movie == null)
            {
                return View("Error", new ErrorViewModel(404, "Requested information could not be found"));
            }

            if (movie.Producer == null)
            {
                movie.Producer = new Producer();
            }

            var model = new ViewMovieViewModel
            {
                Movie = movie
            };

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var movie = _movieDbService.GetById(id);
            var producers = _producerDbService.GetAll()?.OrderBy(x => x.FirstName).ToList();
            var allActors = _actorDbService.GetAll()?.OrderBy(x => x.FirstName).ToList();
            var actorsInMovie = new List<Actor>();

            if (movie != null)
            {
                actorsInMovie = _movieDbService.GetMovieActors(movie.Id).ToList();
            }

            if (producers == null)
            {
                producers = new List<Producer>();
            }

            if (allActors == null)
            {
                allActors = new List<Actor>();
            }

            MovieViewModel listingResult;

            try
            {
                listingResult = new MovieViewModel()
                {
                    Id = movie.Id,
                    MovieName = movie.Name,
                    Plot = movie.Plot,
                    ReleaseYear = movie.ReleaseYear,
                    PosterUrl = movie.PosterUrl,
                    CurrentPoster = movie.PosterUrl,
                    MovieActors = actorsInMovie,
                    AllActors = ProjectToActorCheckboxModelList(allActors, actorsInMovie),
                    Producers = producers,
                    CurrentProducerId = movie.Producer?.Id ?? 0,
                    PersonViewModel = new PersonViewModel(_genders)
                };
            }
            catch (Exception ex)
            {
                if (id != 0)
                {
                    return RedirectToAction("Error", new { message = "Invalid movie request" });
                }

                listingResult = new MovieViewModel()
                {
                    AllActors = ProjectToActorCheckboxModelList(allActors, actorsInMovie),
                    Producers = producers,
                    PersonViewModel = new PersonViewModel(_genders)
                };
            }

            return View(listingResult);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MovieViewModel movieVm)
        {
            // Check if ModelState is valid before proceeding
            ReloadMovieViewModel(movieVm);

            var newActors = new List<Actor>();
            var newPosterUrl = string.Empty;
            var currentMovieActors = _movieDbService.GetMovieActors(movieVm.Id); // Currently mapped to movie to keep + those that need to be removed from mapping. Current movie actors before updating
            try
            {
                var valid = true;
                valid &= ValidateMovie(movieVm);
                valid &= ValidateReleaseYear(movieVm);
                valid &= ValidateAndUpdateCurrentProducer(movieVm);
                valid &= ValidateAndUpdateMovieActors(movieVm, newActors);
                var validPoster = ValidatePosterAndGetPosterUrl(movieVm.Poster, out newPosterUrl);
                valid &= validPoster;

                if (!valid)
                {
                    if (movieVm.Poster != null && validPoster)
                    {
                        ModelState.AddModelError("Poster", "Please reselect poster");
                        ModelState.AddModelError("GlobalError", "Please reselect poster");
                    }

                    return View("Edit", movieVm);
                }

                if (!ModelState.IsValid)
                {
                    return View("Edit", movieVm);
                }

                _currentMovie = _movieDbService.GetById(movieVm.Id);
                movieVm.PosterUrl = newPosterUrl;
                SaveMovie(movieVm, newActors, currentMovieActors);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { ex.Message });
            }

            return RedirectToAction("Movie", new { id = _currentMovie.Id });
        }
        
        [Route("Listing/Error/{code:int?}")]
        public IActionResult Error(int code, string message = null)
        {
            if (code == 0)
            {
                code = 404;
            }
            if (string.IsNullOrWhiteSpace(message))
            {
                message = "Requested information could not be found";
            }
            var model = new ErrorViewModel(code, message);

            return View(model);
        }

        #region Supporting Methods

        private bool ValidateMovie(MovieViewModel movieVm)
        {
            if (movieVm.Id == 0)
            {
                if (_movieDbService.GetMovie(movieVm.MovieName, movieVm.ReleaseYear) != null)
                {
                    ModelState.AddModelError("GlobalError", "Movie already exists");
                    return false;
                }

                return true;
            }

            if (_movieDbService.GetById(movieVm.Id) == null)
            {
                throw new Exception("Invalid movie request");
            }

            return true;
        }

        private void SaveMovie(MovieViewModel movieVm, List<Actor> newActors, IEnumerable<Actor> currentMovieActors)
        {
            var errors = new StringBuilder();
            var actorsToRemove = new List<int>();
            int errorCount = 0;

            // Save producer
            try
            {
                if (movieVm.NewProducerId < 1 || movieVm.CurrentProducerId != movieVm.NewProducerId)
                {
                    movieVm.NewProducerId = SaveProducer(movieVm.NewProducer);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            // Save new actors
            try
            {

                newActors = SaveNewActors(movieVm, newActors, currentMovieActors);

                actorsToRemove = currentMovieActors
                    .Where(x => movieVm.MovieActors.FirstOrDefault(y => y.Id == x.Id) == null)?
                    .Select(result => result.Id)
                    .ToList();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            // Save movie

            if (_currentMovie == null)
            {
                _currentMovie = new Movie();
            }
            _currentMovie.Name = movieVm.MovieName;
            _currentMovie.Plot = movieVm.Plot;
            _currentMovie.PosterUrl = string.IsNullOrWhiteSpace(movieVm.PosterUrl) ? movieVm.CurrentPoster : movieVm.PosterUrl;
            _currentMovie.ReleaseYear = movieVm.ReleaseYear;
            _currentMovie.Producer = movieVm.NewProducer;

            int count = 0;
            try
            {
                count = _movieDbService.Update(_currentMovie);

                if (count != 1)
                {
                    if (_currentMovie == null)
                    {
                        throw new Exception("Failed to add movie");
                    }

                    throw new Exception("Failed to update movie");
                }
            }
            catch (Exception ex)
            {
                throw ex;

PracticeMovieDbProject/Controllers/ProducerController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieData;
using PracticeMovieDbProject.ViewModels;

namespace PracticeMovieDbProject.Controllers
{
    public class ProducerController : Controller
    {
        private IMovieService _movieDbService;
        private IActorService _actorDbService;
        private IProducerService _producerDbService;
        private IGenderService _genderDbService;

        public ProducerController(IMovieService movies, IActorService actors, IProducerService producers, IGenderService genders)
        {
            _movieDbService = movies;
            _actorDbService = actors;
            _producerDbService = producers;
            _genderDbService = genders;
        }

        public IActionResult Index()
        {
            var producers = _producerDbService.GetAll();

            if (producers == null)
            {
                return RedirectToAction("Error", "Listing");
            }

            var listingResult = producers
                .Select(result => new PersonDetailsViewModel
                {
                    Id = result.Id,
                    Name = result.FullName,
                    DOB = result.DOB.ToString("MM/dd/yyyy"),
                    Age = result.Age,
                    Sex = result.Sex.Description,
                    Bio = result.Bio
                })
                .OrderBy(x => x.Name);

            var model = new ProducersListingViewModel()
            {
                Producers = listingResult
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var producer = _producerDbService.GetById(id);

            if (producer == null)
            {
                return RedirectToAction("Error", "Listing");
            }

            var model = new PersonDetailsViewModel
            {
                Id = producer.Id,
                Name = producer.FullName,
                DOB = producer.DOB.ToString("MM/dd/yyyy"),
                Age = producer.Age,
                Bio = producer.Bio,
                Sex = producer.Sex.Description,
                Movies = _producerDbService.GetProducerMovies(id)
            };

            return View(model);
        }
    }
}

PracticeMovieDbProject/Views/Listing/Index.cshtml
@model MovieListingViewModel
@{
    ViewBag.Title = "Movie Listings";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/posters/Black Panther.jpg" alt="Black Panther" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    <h1 class="text-info">Black Panther</h1>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/posters/Jurassic World - Fallen Kingdom.jpg" alt="Jurassic World - Fallen Kingdom" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    <h1 class="text-info">Jurassic World - Fallen Kingdom</h1>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-12">
        <h3 class="text-muted">@ViewBag.Title</h3>
        <div id="moviesTable">
            <table class="table table-condensed" id="moviesTable">
                <tbody>
                    @foreach (var movie in Model.Movies)
                    {
                        var releaseYear = "";
                        if (movie.ReleaseYear > 0)
                        {
                            releaseYear = "(" + movie.ReleaseYear + ") ";
                        }
                        else
                        {
                            releaseYear = "";
                        }
                        <tr class="movieRow">
                            <td>
                                @{
                                    var moviePoster = "/images/posters/No_Image_Available.gif";
                                    if (!string.IsNullOrWhiteSpace(movie.PosterUrl))
                                    {
                                        moviePoster = "/images/" + movie.PosterUrl;
                                    }
                                }

                                <a asp-controller="Listing" asp-action="Movie" asp-route-id="@movie.Id">
                                    <img src="@moviePoster" class="rectangularImage" />
                                </a>
                            </td>
                            <td>
                                <div>
                                    <a class="movieHeader" asp-controller="Listing" asp-action="Movie" asp-route-id="@movie.Id">@movie.MovieName</a>
                                    <span class="textLarge"> @releaseYear</span>
                                </div>
                                <div> @movie.Plot </div>
                                <div class="topMarginOnly">
                                    <span class="boldGrayText">Producer: </span>
                                    <a asp-controller="Producer" asp-action="Detail" asp-route-id="@movie.CurrentProducerId">@movie.ProducerName</a>
                                </div>
                                <div>
                                    <span class="boldGrayText">Actors: </span>

                                    @{
                                        string endChar = "";
                                        int i = 1;
                                        foreach (var actor in movie.MovieActors)
                                        {
                                            if (actor.Id != movie.MovieActors.Last().Id)
                                            {
                                                if (i == 3)
                                                {
                                                    endChar = " . . .";
                                                    <a asp-controller="Actor" asp-action="Detail" asp-route-id="@actor.Id">@actor.FullName</a><span>,</span>
                                                    <a asp-controller="Listing" asp-action="Movie" asp-route-id="@movie.Id">@endChar</a>
                                                    break;
                                                }
                                                else
                                                {
                                                    endChar = ", ";
                                                }
                                            }
                                            else
                                            {
                                                endChar = "";
                                            }

                                            <a asp-controller="Actor" asp-action="Detail" asp-route-id="@actor.Id">@actor.FullName</a>@endChar
                                            i++;
                                        }
                                    }
                                </div>
                            </td>
                            <td>
                                <a asp-controller="Listing" asp-action="Edit" asp-route-id="@movie.Id">
                                    <button class="btn btn-sm btn-info">Edit</button>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

PracticeMovieDbProject/Views/Listing/Movie.cshtml
@model ViewMovieViewModel
@{
    ViewBag.Title = Model.Movie.Name;
    var releaseYear = "";
    if (Model.Movie.ReleaseYear > 0)
    {
        releaseYear = "(" + Model.Movie.ReleaseYear + ") ";
    }

    var moviePoster = "/images/posters/No_Image_Available.gif";
    if (!string.IsNullOrWhiteSpace(Model.Movie.PosterUrl))
    {
        moviePoster = "/images/" + Model.Movie.PosterUrl;
    }

    var noProducerInfo = "No producer information available.";
}

<div class="jumbotron">
    <div class=" row">
        <div class="col-md-4">
            <div>
                <img class="squareImage" src="@moviePoster" alt="@Model.Movie.Name" />
            </div>
        </div>
        <div class="col-md-8 detailPanel">
            <p>
                <span class="movieHeader">@Model.Movie.Name </span>  @releaseYear
                <a asp-controller="Listing" asp-action="Edit" asp-route-id="@Model.Movie.Id">
                    <button class="btn btn-sm btn-info">Edit</button>
                </a>
            </p>

            <strong>Plot:</strong> @Model.Movie.Plot
            <br /><br />

            <strong>Producer:</strong>
            @if (!string.IsNullOrWhiteSpace(@Model.Movie.Producer.FullName))
            {
                <a asp-controller="Producer" asp-action="Detail" asp-route-id="@Model.Movie.Producer.Id">@Model.Movie.Producer.FullName</a>
            }
            else
            {
                <span>@noProducerInfo</span>
            }
            <br />

            <strong>Actors</strong>
            <ul>
                @if (Model.Movie.Actors != null)
                {
                    foreach (var actor in Model.Movie.Actors)
                    {
                        <li>
                            <a asp-controller="Actor" asp-action="Detail" asp-route-id="@actor.Id">@actor.FullName</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</div>

PracticeMovieDbProject/Views/Listing/_AddActor.cshtml
@model PersonViewModel

<div class="padded">
    <div class="row padded">
        <strong class="text-muted">Add Actor</strong>

    </div>
    <div class="row">
        <div class="col-md-9 col-sm-12">
            <form onsubmit="process">

                <div class="row">
                    <div class="col-sm-4 padded">
                        <div class="col-sm">
                            <label> First Name </label><span class="text-danger">*</span>
                            <span id="aFNameReq" class="text-danger"></span>
                        </div>
                        <div class="col-sm">
                            <input type="text" id="aFName" placeholder="First Name" class="widthFull" />
                        </div>
                    </div>
                    <div class="col-sm-4 padded">
                        <div class="col-sm">
                            <label> MiddleName </label>
                        </div>
                        <div class="col-sm">
                            <input type="text" id="aMName" placeholder="Middle Name" class="widthFull" />
                        </div>
                    </div>
                    <div class="col-sm-4 padded">
                        <div class="col-sm">
                            <label> Last Name </label><span class="text-danger">*</span>
                            <span id="aLNameReq" class="text-danger"></span>
                        </div>
                        <div class="col-sm">
                            <input type="text" id="aLName" placeholder="Last Name" class="widthFull" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 padded">
                        <div class="col-sm">
                            <label> Date of Birth </label>
                            <span id="aDobReq" class="text-danger"></span>
                        </div>
                        <div class="col-sm">
                            <input type="date" id="aDob" class="widthFull" value="0001-01-01" />
                        </div>
                    </div>
                    <div class="col-sm-6 padded">
                        <div class="col-sm">
                            <label> Sex </label><span class="text-danger">*</span>
                            <span id="aSexReq" class="text-danger"></span>
                        </div>
                        <div class="col-sm">
                            @foreach (var gender in Model.SexOptions)
                            {
                                <label class="radio-inline">
                                    <input type="radio" id="aSex" name="aSex" class="radio-inline" value="@gender.Description" />@gender.Description
                                </label>
                            }
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 padded">
                        <div class="col-sm">
                            <label> Bio </label>
                        </div>
                        <div class="col-sm">
                            <textarea rows="5" id="aBio" class="widthFull"></textarea>
                        </div>
                    </div>
                </div>

                <div class="row padded">
                    <button type="button" onclick="addNewActor()" class="btn btn-info btn-sm">Add</button>
                    <button type="reset" class="btn btn-info btn-sm">Reset</button>
                    <button type="button" onclick="hideActorDiv()" class="btn btn-info btn-sm">Close</button>
                </div>
            </form>
        </div>

        <!-- Display new producers that are being added -->
        <div class="col-md-3 col-sm-12 left-grey-borderline background-whitesmoke" id="newActorsDisplay">
            <span class="text-muted">
                <strong>Actors</strong>
            </span>
            <div id="aItemListDiv">
                <ul id="actorItem"></ul>
            </div>
        </div>

    </div>
</div>