PracticeMovieDbProject/Controllers/ActorController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieData;
using PracticeMovieDbProject.ViewModels;

namespace PracticeMovieDbProject.Controllers
{
    public class ActorController : Controller
    {
        private IMovieService _movieDbService;
        private IActorService _actorDbService;
        private IProducerService _producerDbService;
        private IGenderService _genderDbService;

        public ActorController(IMovieService movies, IActorService actors, IProducerService producers, IGenderService genders)
        {
            _movieDbService = movies;
            _actorDbService = actors;
            _producerDbService = producers;
            _genderDbService = genders;
        }
        
        public IActionResult Index()
        {
            var actors = _actorDbService.GetAll();
            
            if (actors == null)
            {
                return RedirectToAction("Error", "Listing");
            }

            var listingResult = actors
                .Select(result => new PersonDetailsViewModel
                {
                    Id = result.Id,
                    Name = result.FullName,
                    DOB = result.DOB.ToString("MM/dd/yyyy"),
                    Age = result.Age,
                    Sex = result.Sex.Description,
                    Bio = result.Bio
                })
                .OrderBy(x => x.Name);

            var model = new ActorsListingViewModel()
            {
                Actors = listingResult
            };

            return View(model);
        }

        public IActionResult Detail(int? id)
        {
            if(!id.HasValue)
            {
                return RedirectToAction("Error", "Listing");
            }

            var actor = _actorDbService.GetById(id.Value);
            
            if(actor == null)
            {
                return RedirectToAction("Error", "Listing");
            }

            var model = new PersonDetailsViewModel
            {
                Id = actor.Id,
                Name = actor.FullName,
                DOB = actor.DOB.ToString("MM/dd/yyyy"),
                Age = actor.Age,
                Bio = actor.Bio,
                Sex = actor.Sex.Description,
                Movies = _actorDbService.GetActorMovies(id.Value)
            };

            return View(model);
        }
    }
}

PracticeMovieDbProject/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieData;
using MovieData.Models;
using PracticeMovieDbProject.ViewModels;

namespace PracticeMovieDbProject.Controllers
{
    public class EditorController : Controller
    {
        private IMovieService _movieDbService;
        private IActorService _actorDbService;
        private IProducerService _producerDbService;
        private IGenderService _genderDbService;
        private IMappingService _mappingService;
        private static IEnumerable<Gender> _genders;

        public EditorController(IMovieService movies,
            IActorService actors,
            IProducerService producers,
            IGenderService genders,
            IMappingService mappings)
        {
            _movieDbService = movies;
            _actorDbService = actors;
            _producerDbService = producers;
            _genderDbService = genders;
            _mappingService = mappings;
            _genders = _genderDbService.GetGenders();
        }

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Listing");
        }

        public IActionResult NewProducer()
        {
            var model = new PersonViewModel
            {
                PersonType = PersonType.Producer,
                SexOptions = _genders
            };

            return View(model);
        }

        public IActionResult NewActor()
        {
            var model = new PersonViewModel
            {
                PersonType = PersonType.Actor,
                SexOptions = _genders
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NewProducer(PersonViewModel personVm)
        {
            if (!ModelState.IsValid)
            {
                personVm.SexOptions = _genders;
                return View("NewProducer", personVm);
            }

            var gender = _genderDbService.GetGenders().FirstOrDefault(x => x.Description == personVm.Sex);
            var newProducer = new Producer()
            {
                FirstName = personVm.FirstName,
                MiddleName = personVm.MiddleName,
                LastName = personVm.LastName,
                DOB = personVm.DOB,
                Bio = personVm.Bio,
                Sex = gender
            };

            try
            {
                _producerDbService.Add(newProducer);
            }
            catch (ArgumentException argEx)
            {
                return RedirectToAction("Error", "Listing", new { message = argEx.Message });
            }
            catch (Exception ex)
            {
                // Log exception and display friendly message to user
                return RedirectToAction("Error", "Listing", new { message = "Looks like something went wrong" });
            }

            var producer = _producerDbService.GetProducer(newProducer.FirstName, newProducer.MiddleName, newProducer.LastName, newProducer.DOB, newProducer.Sex);

            if (producer != null)
            {
                return RedirectToAction("Detail", "Producer", new { id = producer.Id });
            }

            return RedirectToAction("Index", "Producer");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NewActor(PersonViewModel personVm)
        {
            if (!ModelState.IsValid)
            {
                personVm.SexOptions = _genders;
                return View("NewActor", personVm);
            }

            var gender = _genderDbService.GetGenders().FirstOrDefault(x => x.Description == personVm.Sex);

            var newActor = new Actor()
            {
                FirstName = personVm.FirstName,
                MiddleName = personVm.MiddleName,
                LastName = personVm.LastName,
                DOB = personVm.DOB,
                Bio = personVm.Bio,
                Sex = gender
            };

            try
            {
                _actorDbService.Add(newActor);
            }
            catch (ArgumentException argEx)
            {
                return RedirectToAction("Error", "Listing", new { message = argEx.Message });
            }
            catch (Exception ex)
            {
                // Log exception and display friendly message to user
                return RedirectToAction("Error", "Listing", new { message = "Looks like something went wrong" });
            }

            var actor = _actorDbService.GetActor(newActor.FirstName, newActor.MiddleName, newActor.LastName, newActor.DOB, newActor.Sex);

            if (actor != null)
            {
                return RedirectToAction("Detail", "Actor", new { id = actor.Id });
            }

            return RedirectToAction("Index", "Actor");
        }
    }
}

PracticeMovieDbProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <link rel="stylesheet" href="~/css/styles.css" />

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Listing" asp-action="Index" class="navbar-brand">MovieDb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Listing" asp-action="Index">Movie Listings</a></li>
                    <li><a asp-area="" asp-controller="Actor" asp-action="Index">Actors</a></li>
                    <li><a asp-area="" asp-controller="Producer" asp-action="Index">Producers</a></li>
                    <li><a asp-area="" asp-controller="Listing" asp-action="Edit" asp-route-id="0">Add Movie</a></li>
                    <li><a asp-area="" asp-controller="Editor" asp-action="NewActor">Add Actor</a></li>
                    <li><a asp-area="" asp-controller="Editor" asp-action="NewProducer">Add Producer</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MovieDb by Abhilash Hazarika</p>
        </footer>
    </div>
</body>
</html>